---
services:
  personal-site:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 8080:80
    image: ghcr.io/arnevdk/personal-site:latest

  personal-site-dev:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html:ro,z
      - ./nginx.conf:/etc/nginx/conf.d/999-personal-site.conf:ro,z
    image: ghcr.io/arnevdk/personal-site:latest
