server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    root   /usr/share/nginx/html;

    location / {
        index  index.html;
    }

    location /files {
    	autoindex on;
    }

    location ~ ^/cite/.*\.bib$ {
        add_header Content-Type text/plain;
        add_header Content-Disposition inline;
    }


    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}
