
name: Build and Publish to GitHub Container Registry

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build from compose.yml
        run: |
          docker compose -f compose.yml build

      - name: Push to GHCR
        run: |
          docker compose -f compose.yml push
